apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-kube-prometheus-stack-alertmanager
  namespace: monitoring
data:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
    route:
      receiver: "default"
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
    receivers:
      - name: "default"
        webhook_configs:
          - url: "http://example.com/webhook"
