#Persistent Storage
persistence:
  enabled: false
  type: pvc
  size: 5Gi
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  volumeBindingMode: Immediate
  finalizers:
    - kubernetes.io/pvc-protection

securityContext:
  runAsUser: 472
  runAsGroup: 472
  fsGroup: 472


#Ingress Configuration (Traefik)
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
  hosts:
    - grafana.local
  path: /
  tls: []

#Admin Credentials
adminUser: admin
adminPassword: jacobsm14

#Data Source (Auto-connect to Prometheus)
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus-1
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        isDefault: true

#UI & Dashboards
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: Default
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

dashboardsConfigMaps: {}
dashboards: {}

#Service
service:
  type: ClusterIP
  port: 80
  targetPort: 3000
