alertmanager:
  enabled: true

#persistent storage + ingress
server:
  persistentVolume:
    enabled: true
    size: 8Gi
    storageClass: local-path
  retention: 15d

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - prometheus.local
    paths:
      - /
    tls: []

  alertingEndpoints:
    - name: alertmanager
      namespace: monitoring
      service: prometheus-alertmanager
      port: 9093

#alerting rules
serverFiles:
  alerts:
    groups:
    - name: resource-alerts
      rules:
      - alert: HighNodeCPU
        expr: 100 - (avg by (instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU on {{ $labels.instance }}"
          description: "Node CPU usage > 85% for 5 minutes."

      - alert: HighNodeMemory
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Node memory used > 85% for 5 minutes."

#service monitor
serviceAccounts:
  server:
    create: true

service:
  type: ClusterIP
  port: 80
  targetPort: 9090

#node exporter
prometheus-node-exporter:
  hostRootFsMount:
    enabled: false
  tolerations:
    - operator: "Exists"
  resources:
    requests:
      cpu: 50m
      memory: 50Mi
    limits:
      cpu: 100m
      memory: 100Mi

extraScrapeConfigs: |
  - job_name: 'pakalspot-backend'
    metrics_path: /metrics
    scrape_interval: 15s
    static_configs:
      - targets:
          - 'pakalspot-dev-pakalspot-chart-backend.pakalspot-dev.svc.cluster.local:80'