apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pakalspot-frontend-env
  namespace: pakalspot-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets
  target:
    name: pakalspot-frontend-env
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        env-config.js: |
          window.__ENV = {
            GOOGLE_MAPS_API_KEY: "{{ .GOOGLE_MAPS_API_KEY }}",
            VITE_GOOGLE_MAPS_API_KEY: "{{ .GOOGLE_MAPS_API_KEY }}",
            API_URL: "/api"
          };
  data:
    - secretKey: GOOGLE_MAPS_API_KEY
      remoteRef:
        key: /pakalspot/prod/frontend
        property: GOOGLE_MAPS_API_KEY
